services:
  honeypot:
    build: .
    container_name: iot_honeypot
    ports:
      # Dashboard & API Port
      - "5000:5000"
      # Honeypot Service Ports
      - "8080:8080" # Fake IP Camera (HTTP)
      - "2323:2323" # Fake Telnet
      - "1883:1883" # Fake MQTT
    volumes:
      # This is crucial: it saves the SQLite DB and JSON logs to your local disk
      # so data persists even if the container is removed and rebuilt.
      - ./app/db:/app/db
    restart: unless-stopped
