version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/honeypot.db
      - GEOIP_DB_PATH=/app/data/GeoLite2-City.mmdb
      - BIND_ADDR=0.0.0.0
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
    volumes:
      - data:/app/data
    depends_on:
      - init-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; import sys; sys.exit(0 if requests.get('http://localhost:8000/api/v1/stats').status_code == 200 else 1)\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  ssh-honeypot:
    build: ./honeypots/ssh
    ports:
      - "22222:2222"
    environment:
      - BIND_ADDR=0.0.0.0
      - SSH_PORT=2222
      - BACKEND_URL=http://backend:8000
    volumes:
      - data:/app/data
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  http-honeypot:
    build: ./honeypots/http
    ports:
      - "808:8080"
    environment:
      - BIND_ADDR=0.0.0.0
      - HTTP_PORT=8080
      - BACKEND_URL=http://backend:8000
    volumes:
      - data:/app/data
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    # Removed chmod commands for Windows
    command: python -u server.py

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  init-db:
    build: ./backend
    command: ["python", "scripts/init_db.py"]
    volumes:
      - data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/honeypot.db
    restart: "no"

volumes:
  data:
    driver: local
